### ISSUE TITLE
Latest version not available in pypi

### ISSUE THREAD

**Issue by agalazis** [crccheck/django-object-actions#101]
Hello, latest version available in change log is not available to pypi I guess something broke or the script that pushes it there doesn't work

**Comment by crccheck** [comment]
it looks like PyPI suddenly doesn't like the restructured text and refuses to accept the package. I have no idea what's wrong as it renders in my previews.

**Comment by crccheck** [comment]
in #94, I was going to switch to Markdown. That would fix things.

**Comment by crccheck** [comment]
1.1.2 is on PyPI https://pypi.org/project/django-object-actions/
