### ISSUE TITLE
Instead of getting only the checked objects, I receive query with all the entities in the table

### ISSUE THREAD

**Issue by DanailDimitrovx2** [crccheck/django-object-actions#114]
Hello guys,
Is it possible to use the check boxes in the admin UI to filter only the objects that I would like to take place in the queryset, sent to my function? I red the documentation of the package couple of times but couldn't realize how to achieve this. For the moment, it doesn't matter if I have checked something, none or all, I am getting full list of all the objects in the table. It's a great package, though, thank you for sharing it with us :) :100:

**Comment by crccheck** [comment]
no, there isn't a great way to just get the checked items. I actually did this on purpose, because Django already has something for that. If you want to use the checked items, you Django Admin Actions https://docs.djangoproject.com/en/3.1/ref/contrib/admin/actions/

It's possible to use the same function as an admin action and for this plugin though!

**Comment by DanailDimitrovx2** [comment]
> 
> 
> no, there isn't a great way to just get the checked items. I actually did this on purpose, because Django already has something for that. If you want to use the checked items, you Django Admin Actions https://docs.djangoproject.com/en/3.1/ref/contrib/admin/actions/
> 
> It's possible to use the same function as an admin action and for this plugin though!

**Comment by DanailDimitrovx2** [comment]
The bussiness requirement is to have this option attached at a button, not at the actions dropdown. Do you think there is some workaround, which I can research for? I was thinking eventually if it would be possible if through the button there is a way to activate the action. The other option was to search through the query and to choose only the objects which checkboxes are checked. Unfortunately I couldn't find much information about ways in which I could get information from this checkboxes. Excuse me for the ignorance, I am new to Dajngo and still exploring the possibilities of the framework. If you can point me just the direction it makes sense to dig into,I will be grateful.

**Comment by crccheck** [comment]
I can think of a few options, but they're all pretty hacky. Somehow getting a html form button that does the same form submission is what I'd try to get working
