### ISSUE TITLE
Add label/description decorator for "cleaner" code

### ISSUE THREAD

**Issue by wolph** [crccheck/django-object-actions#115]
Perhaps it's something that only irks me, but I find that this syntax quickly becomes readable after the function goes beyond a few lines:

 ```python
    def publish_this(self, request, obj):
        publish_obj(obj)
    publish_this.label = "Publish"  # optional
    publish_this.short_description = "Submit this article"  # optional
```

I'm currently using this little decorator to take care of the labels and description which works great:
```python
def create_action(label=None, short_description=None):

    def _create_action(function):
        if label:
            function.label = label

        if short_description:
            function.short_description = short_description

        return function

    return _create_action
```

Usage is like this:
```python
    @create_action('Publish', 'Submit this article')
    def publish_this(self, request, obj):
        publish_obj(obj)
```

**Comment by crccheck** [comment]
neat. It bugs me too but I was copying how a lot Django admin stuff does. I haven't checked out those docs in awhile though. I worry about "There should be one-- and preferably only one --obvious way to do it." from [PEP 20](https://www.python.org/dev/peps/pep-0020/)

These assignments create a lot of annoying mypy errors too.

**Comment by crccheck** [comment]
if the Django admin has this pattern now then ya we should definitely do it!

**Comment by WoLpH** [comment]
With regards to the Zen of Python, I think Django has been lost from the beginning. It's filled with (meta) magic all over so there's no real clean way anymore.

A cleaner way to do it would have been similar to argparse: https://docs.python.org/3/library/argparse.html#example
So instead of having a list/tuple of actions, you would have something like:
```python
actions = Actions()

@actions.add_action(label=label, ...)
def my_action(self, request, obj):
    ...
```

That would still work regular functions too if you wanted:
```python
actions.add_action(label=label, ...)(some_function)
```
Or perhaps better:
```python
actions.add_action(some_function, label=label, ...)
```

Note that I used keyword arguments for the `label` here so a simple version like this (without passing arguments to the decorator) would still work:
```python
@actions.add_action
def my_action(self, request, obj):
    ...
```

**Comment by WoLpH** [comment]
It doesn't look like Django is doing something like this yet: https://docs.djangoproject.com/en/3.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_display

I still see `decade_born_in.short_description = ...` in the documentation. But a universal decorator could be made easily:

```python
def set_attributes(**kwargs):
    def _set_attributes(function):
        for key, value in kwargs.items():
            setattr(function, key, value)
        return function
    return _set_attributes
```

**Comment by crccheck** [comment]
Great thoughts @WoLpH. It sounds like a universal-ish decorator would be a better way to solve this than to scope it to just this package.

**Comment by WoLpH** [comment]
That's fair I guess, I'll add it to my Django Utils library in that case: https://pypi.org/project/django-utils2/

**Comment by WoLpH** [comment]
Well... great minds think alike. It seems that the Django development release has this feature: https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.display

**Comment by WoLpH** [comment]
While we're still stuck with older Django versions, the python-utils package now has this included. This is a pure-python package I maintain which is available through the repo in most BSD/Linux distributions.

https://python-utils.readthedocs.io/en/latest/python_utils.html#python_utils.decorators.set_attributes

**Comment by alfonsrv** [comment]
> Well... great minds think alike. It seems that the Django development release has this feature: https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.display

Unfortunately this decorator cannot be used with `django-object-actions`. `@admin.display(description='Test')` doesn't work and `@admin.display(label='Test')` raises an exception.

**Comment by crccheck** [comment]
Interesting! I'll look into seeing what it'll take to get it to work... one day

**Comment by Alexerson** [comment]
I reused the same logic that is now in the django project. The test is a bit tautological, but at least it’s here. Let me know if you have any suggested changes.

**Comment by alfonsrv** [comment]
New release on pypi?

**Comment by crccheck** [comment]
There was some sort of cleanup thing I was going to do before a release but now I can't remember. So I'll just hit the button to release!
