### ISSUE TITLE
why does get_change_actions return a reference to self.change_actions?

### ISSUE THREAD

**Issue by jws** [crccheck/django-object-actions#172]
why does [`get_change_actions` return a reference to `self.change_actions`](https://github.com/crccheck/django-object-actions/blob/98aad50f07f167de41ec0fa4fc348de3132840c5/django_object_actions/utils.py#L88)? is there an use case for such behavior?
- the behavior seems intentional given:
  - [test logic using `id` check](https://github.com/crccheck/django-object-actions/blob/98aad50f07f167de41ec0fa4fc348de3132840c5/django_object_actions/tests/test_utils.py#L39)
  - [readme calling `list()` explicitly over the result of `get_change_actions()`](https://github.com/crccheck/django-object-actions/blame/98aad50f07f167de41ec0fa4fc348de3132840c5/README.rst#L131)
    - I would argue the implications of calling `list()` in the readme is not obvious without a deep understanding here.   
- however, this makes it easy, and surprising (!), to write unsafe code that changes the model admin's `change_actions` definition in one request, and have that change persist across multiple requests.
  - a safer default approach would be to return a copy of `self.change_actions` instead.

**Comment by crccheck** [comment]
It's a copy of a standard pattern I've seen in Django
