### ISSUE TITLE
@takes_instance_or_queryset with instance doesn't work with update

### ISSUE THREAD

**Issue by AlexRiina** [crccheck/django-object-actions#40]
Related to https://github.com/crccheck/django-object-actions/pull/39 the instance is set in QuerysetIsh, but is ignored in `update()` calls like https://github.com/crccheck/django-object-actions/blob/master/README.rst#re-using-admin-actions

I've added a test in my pull requests which demonstrates the error as well as a potential fix.

**Comment by crccheck** [comment]
Fixed in #39
