### ISSUE TITLE
500 on prefixing pk with "%20" in URL

### ISSUE THREAD

**Issue by tuky** [crccheck/django-object-actions#66]
Lets say you have a model "model" inside the app "app" with object actions enabled and available for this model. Lets also assume, object app.model with pk=13 exists in the DB.

Calling http://localhost:8000/admin/app/model/13/ works.

Calling the detail view like this http://localhost:8000/admin/app/model/%20%2013/ results in an uncaught 500 (NoReverseMatch). The reason should be, that django allows blanks in its admin urls for the pk variable and the django-object-actions URLs don't.

**Comment by crccheck** [comment]
do you have the urlpattern the django admin uses handy?

**Comment by tuky** [comment]
https://github.com/django/django/blob/1.8.13/django/contrib/admin/options.py#L628

**Comment by crccheck** [comment]
I released a new version, 0.9.0. Let me know if that fixes things for you.

**Comment by tuky** [comment]
yes, great. thx!
