### ISSUE TITLE
django-mezzanine template.

### ISSUE THREAD

**Issue by hetii** [crccheck/django-object-actions#7]
For those who use mezzanine cms the template should look like belowe, because it use grappelli:

{% extends "admin/change_form.html" %}
{% load i18n future %}

{% block object-tools %}
{% if change %}
{% if not is_popup %}
    <ul class="object-tools">
    <li><a href="{% url "admin:form_entries" object_id %}">{% trans "View entries" %}</a></li>
    <li><a href="history/" class="historylink">{% trans "History" %}</a></li>
  {% for tool in objectactions %}
    <li class="objectaction-item" data-tool-name="{{ tool.name }}">
      <a href='tools/{{ tool.name }}/' title="{{ tool.short_description }}">
      {{ tool.label|capfirst }}
      </a>
    </li>
  {% endfor %}
    {% if has_absolute_url %}<li><a href="../../../r/{{ content_type_id }}/{{ object_id }}/" class="viewsitelink">{% trans "View on site" %}</a></li>{% endif%}
    </ul>
{% endif %}
{% endif %}

BTW, there should be also a template for admin/change_list.html if we want to have additional action for all items or eg. when we want to have import functionality.

**Comment by crccheck** [comment]
not planning on adding mezzanine support
