### ISSUE TITLE
Django 2 plans

### ISSUE THREAD

**Issue by crccheck** [crccheck/django-object-actions#84]
With Django 2 on the horizon, the plan is to release what I got as v1, trying to get as many of these naming things issues #44 out of the way as possible.

`django-object-actions` will have a v2 release for Django 2 with no backwards compatibility. The v1 release will get basic patches, time permitting

**Comment by danmoz** [comment]
I was just wondering, now that Django 2.0 is officially released, are there any plans for a new release?

Would you accept a Django 2.0 PR that doesn't address the issues in #44?

**Comment by crccheck** [comment]
oof, yeah, sounds good
