### ISSUE TITLE
Switch to Flit for packaging

### ISSUE THREAD

**Issue by crccheck** [crccheck/django-object-actions#94]
https://flit.readthedocs.io/en/latest/index.html

**Comment by crccheck** [comment]
I tested Flit out in https://github.com/crccheck/project_runpy and it was... pretty nice. The downside is you can't `pip install -e` anymore though

**Comment by merwok** [comment]
pip install should work, if you have the right pyproject.toml: https://github.com/caravancoop/configstore/blob/master/pyproject.toml (build-system section, the rest is equivalent to flit.ini)

**Comment by crccheck** [comment]
Thanks, I was going to tackle this soon as cleanup before I start removing support for Django v1 since Django v3 is around the corner.

**Comment by crccheck** [comment]
looks like `pip install -e` still doesn't work:
```
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: xxxxxxxx
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

**Comment by merwok** [comment]
There is an ongoing discussion to determine whether pip editable installs should be pluggable (similar to how pip install can call any build system to get a wheel).  In the meantime, people have to use lower-level mecanisms specific to the build tool, like `python setup.py develop` for setuptools or `flit install --symlink` for flit.

**Comment by crccheck** [comment]
semantic release solves the problems I had with Poetry, so I'm sticking with Poetry
