### ISSUE TITLE
Document _row_actions field in the Readme.md

### ISSUE THREAD

**Issue by gnud** [crccheck/django-object-actions#97]
Hi, it would be lovely if you mention that you can override '_row_actions' field, by inserting it whenever needed in the list_display field of the Admin model class. So that people won't need to read the code to figure that out :).

Thanks,

**Comment by crccheck** [comment]
I'm not sure what this means. Did you mean to open this issue in https://github.com/DjangoAdminHackers/django-admin-row-actions ?

**Comment by gnud** [comment]
No.
